// Sample tasks data
export const initialTasks = [
  {
    id: "task-1",
    title: "Create marketing strategy",
    description: "Develop comprehensive marketing strategy for Q3 campaign launch",
    status: "todo",
    priority: "high",
    dueDate: "2025-04-20",
    assignee: {
      name: "John Doe",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "JD",
    },
  },
  {
    id: "task-2",
    title: "Design social media assets",
    description: "Create graphics for Instagram, Facebook, and Twitter for the new campaign",
    status: "in-progress",
    priority: "medium",
    dueDate: "2025-04-18",
    assignee: {
      name: "Sarah Johnson",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "SJ",
    },
    meeting: {
      title: "Design Review",
      time: "14:30",
      link: "https://meet.google.com/abc-defg-hij",
    },
  },
  {
    id: "task-3",
    title: "Content calendar planning",
    description: "Plan content calendar for the next month including blog posts and social media",
    status: "review",
    priority: "medium",
    dueDate: "2025-04-17",
    assignee: {
      name: "Mike Brown",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "MB",
    },
  },
  {
    id: "task-4",
    title: "SEO optimization",
    description: "Optimize website content for better search engine rankings",
    status: "todo",
    priority: "low",
    dueDate: "2025-04-25",
    assignee: {
      name: "Emily Clark",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "EC",
    },
  },
  {
    id: "task-5",
    title: "Email newsletter design",
    description: "Design template for monthly newsletter",
    status: "in-progress",
    priority: "high",
    dueDate: "2025-04-16",
    assignee: {
      name: "John Doe",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "JD",
    },
  },
  {
    id: "task-6",
    title: "Analytics report",
    description: "Prepare monthly analytics report for the marketing team",
    status: "done",
    priority: "medium",
    dueDate: "2025-04-15",
    assignee: {
      name: "Alex Wong",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "AW",
    },
  },
  {
    id: "task-7",
    title: "Competitor analysis",
    description: "Research and analyze top 5 competitors' marketing strategies",
    status: "review",
    priority: "high",
    dueDate: "2025-04-19",
    assignee: {
      name: "Sarah Johnson",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "SJ",
    },
  },
  {
    id: "task-8",
    title: "Budget planning",
    description: "Prepare Q3 marketing budget proposal",
    status: "todo",
    priority: "high",
    dueDate: "2025-04-22",
    assignee: {
      name: "Mike Brown",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "MB",
    },
  },
  {
    id: "task-9",
    title: "Landing page copy",
    description: "Write copy for new product landing page",
    status: "done",
    priority: "medium",
    dueDate: "2025-04-14",
    assignee: {
      name: "Emily Clark",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "EC",
    },
  },
]

// Sample meetings data
export const initialMeetings = [
  {
    id: "meeting-1",
    title: "Marketing Team Standup",
    date: "2025-04-16",
    time: "09:00",
    participants: 8,
    link: "https://meet.google.com/abc-defg-hij",
  },
  {
    id: "meeting-2",
    title: "Design Review",
    date: "2025-04-16",
    time: "14:30",
    participants: 5,
    link: "https://meet.google.com/jkl-mnop-qrs",
  },
  {
    id: "meeting-3",
    title: "Client Presentation",
    date: "2025-04-16",
    time: "16:00",
    participants: 12,
    link: "https://meet.google.com/tuv-wxyz-123",
  },
  {
    id: "meeting-4",
    title: "Budget Planning",
    date: "2025-04-17",
    time: "11:00",
    participants: 4,
    link: "https://meet.google.com/456-789-abc",
  },
  {
    id: "meeting-5",
    title: "Content Strategy",
    date: "2025-04-18",
    time: "10:30",
    participants: 6,
    link: "https://meet.google.com/def-ghi-jkl",
  },
]
